name: ghidra
version: '11.0.3'
summary: Ghidra SRE tools
description: 'A software reverse engineering (SRE) suite of tools developed by NSA''s
  Research Directorate in support of the Cybersecurity mission |
  '

base: core22
confinement: strict
grade: stable
license: Apache-2.0

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

apps:
  ghidra:
    command: ghidra_11.0.3_PUBLIC/ghidraRun
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-$SNAPCRAFT_TARGET_ARCH
      PATH: $JAVA_HOME/bin:$PATH
      _JAVA_OPTIONS: -Duser.home="$SNAP_USER_DATA"
    plugs:
    - desktop
    - home
    - network-bind
    - x11

  analyzeHeadless:
    command: ghidra_11.0.3_PUBLIC/support/analyzeHeadless
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-$SNAPCRAFT_TARGET_ARCH
      PATH: $JAVA_HOME/bin:$PATH
      _JAVA_OPTIONS: -Duser.home="$SNAP_USER_DATA"
    plugs:
    - desktop
    - home
    - network-bind
    - x11       # still required even for headless operation

parts:
  ghidra:
    plugin: dump
    source: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.0.3_build/ghidra_11.0.3_PUBLIC_20240410.zip
    build-packages:
    - openjdk-17-jre
    - openjdk-17-jdk
    - ca-certificates-java
    - ca-certificates
    stage-packages:
    - openjdk-17-jre
    - openjdk-17-jdk
    - ca-certificates-java
    - ca-certificates
    prime:
      - -usr/lib/jvm/java-11-openjdk-$SNAPCRAFT_TARGET_ARCH/lib/security/blacklisted.certs

