name: ghidra
version: '12.1.2'
summary: Ghidra SRE tools
description: 'A software reverse engineering (SRE) suite of tools developed by NSA''s
  Research Directorate in support of the Cybersecurity mission |

  Includes pyghidra
  '

base: core22
confinement: strict
grade: stable
license: Apache-2.0
icon: snap/gui/ghidra.png
title: Ghidra
website:
  - https://github.com/dclane-code/ghidra-snap/
source-code: 
  - https://github.com/dclane-code/ghidra-snap/
issues:
  - https://github.com/dclane-code/ghidra-snap/issues
contact:
  - https://github.com/dclane-code

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

apps:
  no-python:
    command: ghidra/ghidraRun
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$SNAPCRAFT_TARGET_ARCH
      PATH: $JAVA_HOME/bin:$PATH
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Djava.io.tmpdir=$SNAP_USER_DATA/tmp -Dapplication.tempdir=$SNAP_USER_DATA/tmp -Dapplication.cachedir=$SNAP_USER_DATA/tmp
      GDK_SCALE: "1"
      XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
    plugs:
    - desktop
    - home
    - network
    - network-bind
    - x11
    - removable-media

  analyzeHeadless:
    command: ghidra/support/analyzeHeadless
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$SNAPCRAFT_TARGET_ARCH
      PATH: $JAVA_HOME/bin:$PATH
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA -Djava.io.tmpdir=$SNAP_USER_DATA/tmp -Dapplication.tempdir=$SNAP_USER_DATA/tmp -Dapplication.cachedir=$SNAP_USER_DATA/tmp
    plugs:
    - desktop
    - home
    - network
    - network-bind
    - x11       # still required even for headless operation
    - removable-media

  ghidra:
    command: ghidra/support/pyghidraRun
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$SNAPCRAFT_TARGET_ARCH
      PATH: $JAVA_HOME/bin:$PATH
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Djava.io.tmpdir=$SNAP_USER_DATA/tmp -Dapplication.tempdir=$SNAP_USER_DATA/tmp -Dapplication.cachedir=$SNAP_USER_DATA/tmp
      XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
    plugs:
    - desktop
    - home
    - network
    - network-bind
    - x11
    - removable-media

parts:
  ghidra:
    plugin: dump
    source: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_12.1.2_build/ghidra_12.1.2_PUBLIC_20260605.zip
    build-packages:
    - openjdk-21-jdk
    - ca-certificates-java
    - ca-certificates
    stage-packages:
    - openjdk-21-jdk
    - ca-certificates-java
    - ca-certificates
    organize:
      ghidra_12.1.2_PUBLIC: ghidra
    prime:
      - -usr/lib/jvm/java-11-openjdk-$SNAPCRAFT_TARGET_ARCH/lib/security/blacklisted.certs 
      - -usr/lib/jvm/java-21-openjdk-$SNAPCRAFT_TARGET_ARCH/lib/security/blacklisted.certs
      - -usr/lib/jvm/java-11-openjdk-$SNAPCRAFT_TARGET_ARCH/lib/security/cacerts
      - -usr/lib/jvm/java-21-openjdk-$SNAPCRAFT_TARGET_ARCH/lib/security/cacerts

  pyghidra:
    after: [ghidra]
    plugin: python
    source: .
    build-environment:
     - PIP_NO_INDEx: "true"
     - PIP_FIND_LINKS: "$CRAFT_STAGE/ghidra/Ghidra/Features/PyGhidra/pypkg/dist"
    python-packages:
     - pyghidra
    stage-packages:
    - openjdk-21-jdk
    
